version: '3.9'
services:
  mysql:
    image: mysql:8.0
    container_name: mysql_ecom_container
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: ecom_shop
      MYSQL_USER: penguinnguyen
      MYSQL_PASSWORD: root1234
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
  redis:
    image: redis:latest
    container_name: redis_ecom_container
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
  dev.shoppenguin.com:
    container_name: go_ecom_shoppenguin
    build:
      context: . #lay tat ca file
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - mysql
      - redis
    ports:
      - 8008:8002
volumes:
  mysql_data:
  redis_data: