definitions:
  response.ErrorResponseData:
    properties:
      code:
        description: status code
        type: integer
      detail:
        description: du lai return
      error:
        description: thong bao loi
        type: string
    type: object
  response.ResponseData:
    properties:
      code:
        description: status code
        type: integer
      data: {}
      message:
        type: string
    type: object
  vo.CMSPing_Reply:
    properties:
      mode:
        type: string
      port:
        type: string
    type: object
  vo.CMSPing_Request:
    properties:
      hello:
        description: '@gotags: form:"hello"'
        type: string
    type: object
  vo.UpdatePasswordRegisterInput:
    properties:
      user_password:
        type: string
      user_token:
        type: string
    type: object
  vo.VerifyInput:
    properties:
      verify_code:
        type: string
      verify_key:
        type: string
    type: object
host: localhost:8002
info:
  contact:
    email: hoangnguyendang777@gmail.com
    name: Tips Go
    url: github.com/devpenguin/ecommerce
  description: This is a sample server celler server.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: github.com/devpenguin/ecommerce
  title: Swagger GO Ecommerce API
  version: 1.0.0
paths:
  /auth/update_pass_register:
    post:
      consumes:
      - application/json
      description: When user verify OTP success and update password
      parameters:
      - description: payload
        in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/vo.UpdatePasswordRegisterInput'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.ResponseData'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.ErrorResponseData'
      summary: auth user update password
      tags:
      - auth user management
  /auth/verify_account:
    post:
      consumes:
      - application/json
      description: When user is registered send otp to email
      parameters:
      - description: payload
        in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/vo.VerifyInput'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.ResponseData'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.ErrorResponseData'
      summary: auth user verify otp
      tags:
      - auth user management
  /syst/system-info:
    post:
      consumes:
      - application/json
      description: Lấy về thông tin cơ bản của server , như giờ hệ thống , tên server
        , version hiện tại của hệ thống
      parameters:
      - description: info
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/vo.CMSPing_Request'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/vo.CMSPing_Reply'
      summary: cms Server info
      tags:
      - INFO
swagger: "2.0"
